name: Hello Action

description: My first composite GitHub Action

inputs:
  username:
    description: Name of the user
    required: true

outputs:
  greeting:
    description: Greeting message
    value: ${{ steps.greet.outputs.message }}

runs:
  using: composite

  steps:
    - name: Greet User
      id: greet
      shell: bash
      run: |
        echo "message=Hello ${{ inputs.username }}!" >> $GITHUB_OUTPUT

    - name: Print Date
      shell: bash
      run: date