name: Hello Action

description: My first composite GitHub Action

inputs:
  username:
    description: Name of the user
    required: true

runs:
  using: composite

  steps:
    - name: Greet User
      shell: bash
      run: echo "Hello ${{ inputs.username }}!"

    - name: Print Date
      shell: bash
      run: date