
name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-ci.yml

  display:
    needs: call-workflow
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Version = ${{ needs.call-workflow.outputs.build_version }}"