name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/hello.yml

    with:
      username: "Yash"

    secrets:
      my_secret: ${{ secrets.MY_SECRET }}

  show-output:
    needs: call-workflow
    runs-on: ubuntu-latest

    steps:
      - name: Show returned message
        run: "echo 'Reusable workflow returned: ${{ needs.call-workflow.outputs.message }}'"