name: Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/hello.yml

    with:
      username: "Yash"

    secrets:
      my_secret: ${{ secrets.MY_SECRET }}