name: Docker Compose

on:
  workflow_dispatch:

jobs:
  compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Docker Compose Version
        run: docker compose version

      - name: Start Services
        run: docker compose up -d

      - name: Show Running Containers
        run: docker compose ps

      - name: Show Logs
        run: docker compose logs

      - name: Stop Services
        run: docker compose down