name: Input Demo

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your name"
        required: true

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print Input
        run: echo "Hello ${{ github.event.inputs.username }}"