name: Matrix Include Demo

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node: [20, 22]
        include:
          - node: 20
            environment: development

          - node: 22
            environment: production

    runs-on: ubuntu-latest

    steps:
      - name: Show Matrix Values
        run: |
          echo "Node version: ${{ matrix.node }}"
          echo "Environment: ${{ matrix.environment }}"