name: Day 9 Multi-Dimensional Matrix

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        node-version:
          - 18
          - 20

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Show Node Version
        run: node -v

      - name: Show Matrix Values
        run: echo "OS=${{ matrix.os }} Node=${{ matrix.node-version }}"