name: Reusable CI

on:
  workflow_call:
    outputs:
      build_version:
        description: "Version generated"
        value: ${{ jobs.test.outputs.version }}

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - id: version
        run: echo "version=1.0.0" >> $GITHUB_OUTPUT