name: Variables vs Secrets

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show Variable
        run: echo ${{ vars.APP_NAME }}

      - name: Show Secret
        run: echo ${{ secrets.MY_SECRET }}