name: Secret Env Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ vars.APP_NAME }}

    steps:
      - name: Show Variable
        run: echo $APP_NAME

      - name: Secret Through Env
        env:
          PASSWORD: ${{ secrets.MY_SECRET }}

        run: |
          echo "Variable: $APP_NAME"
          echo "Password: $PASSWORD"