name: Bind Mount

on:
  workflow_dispatch:

jobs:
  bind:
    runs-on: ubuntu-latest

    steps:

      - name: Create Host Directory
        run: mkdir myfolder

      - name: Run Container
        run: |
          docker run -d \
          --name myapp \
          -v $(pwd)/myfolder:/data \
          node:20 sleep 300

      - name: Write File
        run: |
          docker exec myapp sh -c \
          "echo Hello-Yash > /data/test.txt"

      - name: Check Host Files
        run: cat myfolder/test.txt