name: Docker Network

on:
  workflow_dispatch:

jobs:
  network:
    runs-on: ubuntu-latest

    steps:

      - name: Create Network
        run: docker network create mynet

      - name: Run Container 1
        run: |
          docker run -dit \
          --name app1 \
          --network mynet \
          node:20

      - name: Run Container 2
        run: |
          docker run -dit \
          --name app2 \
          --network mynet \
          node:20

      - name: Show Networks
        run: docker network ls

      - name: Inspect Network
        run: docker network inspect mynet

      - name: Resolve app2
        run: docker exec app1 getent hosts app2